"""autogenerated by genpy from f1_rossonet/F1ReadServos.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import f1_rossonet.msg

class F1ReadServos(genpy.Message):
  _md5sum = "38c35486bc1889288de434181d43c782"
  _type = "f1_rossonet/F1ReadServos"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """F1Servos posizione

================================================================================
MSG: f1_rossonet/F1Servos
int16 link1
int16 link2
int16 link3
int16 link4

"""
  __slots__ = ['posizione']
  _slot_types = ['f1_rossonet/F1Servos']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       posizione

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(F1ReadServos, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.posizione is None:
        self.posizione = f1_rossonet.msg.F1Servos()
    else:
      self.posizione = f1_rossonet.msg.F1Servos()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4h.pack(_x.posizione.link1, _x.posizione.link2, _x.posizione.link3, _x.posizione.link4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.posizione is None:
        self.posizione = f1_rossonet.msg.F1Servos()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.posizione.link1, _x.posizione.link2, _x.posizione.link3, _x.posizione.link4,) = _struct_4h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4h.pack(_x.posizione.link1, _x.posizione.link2, _x.posizione.link3, _x.posizione.link4))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.posizione is None:
        self.posizione = f1_rossonet.msg.F1Servos()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.posizione.link1, _x.posizione.link2, _x.posizione.link3, _x.posizione.link4,) = _struct_4h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4h = struct.Struct("<4h")
