controller_list:
  - name: braccio_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: punta_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: false
    joints:
      []


